spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/formulariobd
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

logging:
  level:
    org:
      springframework: DEBUG